Gooru/Gooru-Core-API

- cassandra-core/pom.xml
Latest cassandra version changed
> cassandra latest version 2.0.2

- api/src/main/java/org/ednovo/gooru/domain/service/CollectionServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/userManagement/UserManagementServiceImpl.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/taxonomy/TaxonomyRepositoryHibernate.java
Fixed welcome mail send issue for new regular user
Fixed folder sharing update based on the collection sharing type.
> Fixed welcome mail send issue for new regular user

- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/UserSearchResult.java
- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/UserCio.java
Hi @parthibane  please verify the below code and merge it if correct otherwise let me know the changes.
> Add field for accountTypeId in user search api

- api/src/main/java/org/ednovo/gooru/domain/service/classpage/ClasspageService.java
- api/src/main/java/org/ednovo/gooru/domain/service/classpage/ClasspageServiceImpl.java
- api/src/main/resources/gooruContext-hibernate.xml
- rest-v2-app/src/main/java/org/ednovo/gooru/controllers/v2/api/ClasspageRestV2Controller.java
Changed the logic of join class using auth user details instead of email
address.
added flush mode as commit
> Changed the logic of join class using auth user details instead of email  address

- rest-v2-app/src/main/java/org/ednovo/gooru/controllers/v2/api/CollectionRestV2Controller.java
* This fix is for improve the performance of  reorder API.
> Excluded inner collection  item object  from reorder serialization

- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/ResourceCio.java
- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/SkillCio.java
Verify and merge the below content into core API .if any changes exist please let me know.
> Add the Skill field in Collection index

- api/src/main/java/org/ednovo/gooru/domain/service/CollectionServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/ScollectionService.java
- api/src/main/java/org/ednovo/gooru/domain/service/ScollectionServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/featured/FeaturedServiceImpl.java
- gooru-core/src/main/java/org/ednovo/gooru/core/constant/ParameterProperties.java
- rest-v2-app/src/main/java/org/ednovo/gooru/controllers/v2/api/CollectionRestV2Controller.java
- rest-v2-app/src/main/java/org/ednovo/gooru/controllers/v2/api/FolderRestV2Controller.java
Changed content provider data as optional for get collection API
Changed the custom fields as optional for get collection
Included the skills object in create resource and question API
> added optional support for customFields and contentProvider

- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/ResourceCio.java
Kindly review and merge the code.
> Change variable name

- api/src/main/java/org/ednovo/gooru/domain/service/user/impl/UserServiceImpl.java
This issue is happening when user tries to login via SAML or old login
method of google connect / WSFED.
> added  fix for setting null value for account typeelse {

- api/src/main/java/org/ednovo/gooru/domain/service/FolderService.java
- api/src/main/java/org/ednovo/gooru/domain/service/FolderServiceImpl.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/CollectionRepository.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/CollectionRepositoryHibernate.java
- rest-v2-app/src/main/java/org/ednovo/gooru/controllers/v2/api/FolderRestV2Controller.java
> Added the support for next collection play using filter(using sharing). 

- api/pom.xml
- cassandra-core/pom.xml
- gooru-core/pom.xml
- mail/pom.xml
- rest-v2-app/pom.xml
upgraded maven plugin and fixed the warn message of  servlet-api jar
failed to load on tomat start
> upgraded maven plugin and fixed the servlet-api jar failed to load

- gooru-core/src/main/java/org/ednovo/gooru/core/constant/ParameterProperties.java
kindly merge the code into core api
> Add constans for collection item

- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/StatisticsCo.java
Kindly merge the code for add new fields into statistics.
> Add New fields in statistics

- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/Resource.java
Kindly merge the code for add new fields into resource.
> modify the code based on review

- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/StatisticsCo.java
Kindly merge the code for add new fields into resource.
> Change the name of remixCount

- api/src/main/java/org/ednovo/gooru/domain/service/PartyServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/authentication/AccountServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/AccountEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/ClasspageEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/CollaboratorEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/CollectionEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/ContentEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/FeedbackEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/ResourceEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/SessionEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/eventlogs/UserEventLog.java
- api/src/main/java/org/ednovo/gooru/domain/service/userManagement/UserManagementServiceImpl.java
Conflicts:
api/src/main/java/org/ednovo/gooru/domain/service/classpage/ClasspageServiceImpl.java
> Added copyrights for all the eventlogs

- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/Resource.java
- gooru-core/src/main/java/org/ednovo/gooru/core/cassandra/model/StatisticsCo.java
- rest-v2-app/src/main/java/org/ednovo/gooru/web/spring/interceptor/GooruInterceptor.java
Kindly review this code changes and merge it as soon as possible .
> Add support to Multiple kafka topic support in Search

- api/src/main/java/org/ednovo/gooru/domain/service/session/SessionAcitvityServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/session/SessionActivityService.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/ClassRepository.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/ClassRepositoryHibernate.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/resource/ResourceRepository.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/resource/ResourceRepositoryHibernate.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/session/SessionActivityRepository.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/session/SessionActivityRepositoryHibernate.java
- gooru-core/src/main/java/org/ednovo/gooru/core/constant/ConstantProperties.java
- rest-app/src/main/java/org/ednovo/gooru/controllers/v2/api/SessionActivityRestV2Controller.java
code review changes on session activity
> code review changes on session activity

- api/src/main/java/org/ednovo/gooru/domain/service/ClassServiceImpl.java
- api/src/main/resources/org/ednovo/gooru/domain/model/party/Party.hbm.xml
> added support for update course

- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/RequestMappingUri.java
- rest-app/src/main/java/org/ednovo/gooru/controllers/v1/api/CollectionRestController.java
- rest-app/src/main/java/org/ednovo/gooru/controllers/v1/api/DomainRestController.java
>  Coding Enhancement

- api/src/main/java/org/ednovo/gooru/domain/cassandra/service/BlackListWordCassandraServiceImpl.java
Kindly review the code and letme know if further changes exist.
> add spiltby space instead of expression

- api/src/main/java/org/ednovo/gooru/domain/service/ClassService.java
- api/src/main/java/org/ednovo/gooru/domain/service/ClassServiceImpl.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/ClassRepository.java
- api/src/main/java/org/ednovo/gooru/infrastructure/persistence/hibernate/ClassRepositoryHibernate.java
- api/src/main/resources/org/ednovo/gooru/domain/model/content/ClassCollectionSettings.hbm.xml
- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/ClassCollectionSettings.java
- gooru-core/src/main/java/org/ednovo/gooru/core/api/model/RequestMappingUri.java
- rest-app/src/main/java/org/ednovo/gooru/controllers/v3/api/ClassRestV3Controller.java
added support for update class
> added support for get the class setting details

- api/src/main/java/org/ednovo/gooru/domain/service/collection/AbstractCollectionServiceImpl.java
Conflicts:
gooru-
core/src/main/java/org/ednovo/gooru/core/api/model/RequestMappingUri.java
> Fixed issue in resetSequence

- api/src/main/java/org/ednovo/gooru/domain/service/ScollectionServiceImpl.java
- api/src/main/java/org/ednovo/gooru/domain/service/collection/CollectionBoServiceImpl.java
moved the copy collection item to separate method
> added folder visibility reset logic in move folder method

- gooru-core/src/main/java/org/ednovo/gooru/core/constant/ConstantProperties.java
- rest-app/src/main/java/org/ednovo/gooru/controllers/v2/api/MediaRestV2Controller.java
Reverts Gooru/Gooru-Core-API#1473
> Revert "Added new API for imageCrop"

- api/src/main/java/org/ednovo/gooru/domain/service/collection/CollectionBoServiceImpl.java
1) when resource  sharing is not public.
2) And if it's the question resource.
> Removed the logic of removing the original resource
